### ISSUE TITLE
install test fail

### ISSUE THREAD

**Issue by homopolymer** [yana-safonova/ig_repertoire_constructor#100]
Hi, I ran ./igrec.py --test to verify the installation, but failed and got the following messages.

==== Low Abundant Clusters Remover finished
[Errno 39] Directory not empty: 'igrec_test/dense_sgraph_finder'
Traceback (most recent call last):
  File "./igrec.py", line 956, in main
    RemoveAuxFiles(params)
  File "./igrec.py", line 906, in RemoveAuxFiles
    shutil.rmtree(params.io.dsf_output)
  File "/home/fzeng/anaconda/lib/python2.7/shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/fzeng/anaconda/lib/python2.7/shutil.py", line 254, in rmtree
    os.rmdir(path)
OSError: [Errno 39] Directory not empty: 'igrec_test/dense_sgraph_finder'

ERROR: Exception caught.

In case you have troubles running IgReC, you can write to igtools_support@googlegroups.com.
Please provide us with ig_repertoire_constructor.log file from the output directory.
[Errno 39] Directory not empty: 'igrec_test/dense_sgraph_finder'

**Comment by yana-safonova** [comment]
Hi!

Thank you for your interest in IgRepertoireConstructor! 

This failure looks like troubles with permission. Can you make sure that you have permission to remove directories in your working directory? 

Could you please also try the following command? 
`./igrec.py --test --debug`
Such command keeps all auxiliary files and directories in igrec_test. If the reason is in permission restriction, it should help to finish launch.
